version: "3.9"

services:
  app:
    build: .
    command: npm run dev
    ports: 
      - "3333:3333"
    volumes: 
      - .:/usr/app
  
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DEV_DATABASE_PASSWORD}
      POSTGRES_DB: ${DEV_DATABASE}