version: "3.9"

services:
  app:
    build: .
    command: npm run dev
    ports: 
      - "3333:3333"
    volumes: 
      - .:/usr/app

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
